package tk4;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dwicd
 */
public class formTabelNilai extends javax.swing.JInternalFrame {
    
    Connection conn = controller.database.getDBConn();
    Statement st;
    ResultSet rs;
    String sql;
    public int rerata;
    DefaultTableModel tableModel;
    controller.mahasiswa_model data = new controller.mahasiswa_model();

          
    /**
     * Creates new form formTabelNilai
     */
    public formTabelNilai() {
        initComponents();
        showTable();
        avgTable();
        this.setTitle("Tabel Nilai Mahasiswa");
        tfNilaiRerata2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelNilaiMahasiswa = new javax.swing.JTable();
        btn_keluar = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        tfNilaiRerata2 = new javax.swing.JTextField();
        cb_stats = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        label_nim1 = new javax.swing.JLabel();
        label_nama1 = new javax.swing.JLabel();
        label_rerata1 = new javax.swing.JLabel();
        label_grade1 = new javax.swing.JLabel();
        label_keterangan1 = new javax.swing.JLabel();
        label_nama2 = new javax.swing.JLabel();
        label_nim2 = new javax.swing.JLabel();
        label_rerata2 = new javax.swing.JLabel();
        label_grade2 = new javax.swing.JLabel();
        label_keterangan2 = new javax.swing.JLabel();
        label_detail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelNilaiMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Rerata", "Grade", "Keterangan"
            }
        ));
        tabelNilaiMahasiswa.setColumnSelectionAllowed(true);
        tabelNilaiMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelNilaiMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelNilaiMahasiswa);

        btn_keluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        cb_stats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nilai Rerata", "Jumlah Mahasiswa yang Lulus", "Jumlah Mahasiswa yang Tidak Lulus" }));
        cb_stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_statsActionPerformed(evt);
            }
        });

        label_nim1.setText("NIM :");

        label_nama1.setText("Nama :");

        label_rerata1.setText("Rerata :");

        label_grade1.setText("Grade :");

        label_keterangan1.setText("Keterangan :");

        label_nama2.setText("-");

        label_nim2.setText("-");

        label_rerata2.setText("-");

        label_grade2.setText("-");

        label_keterangan2.setText("-");

        label_detail.setForeground(new java.awt.Color(153, 153, 153));
        label_detail.setText("Detail Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_nama1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(label_nim1)
                                        .addGap(21, 21, 21)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nim2)
                                    .addComponent(label_nama2))
                                .addGap(188, 188, 188)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_rerata1)
                                            .addComponent(label_grade1))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label_grade2)
                                            .addComponent(label_rerata2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label_keterangan1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label_keterangan2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_stats, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNilaiRerata2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(btn_hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_keluar))
                            .addComponent(label_detail))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNilaiRerata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_stats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus)
                    .addComponent(btn_keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_detail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nim1)
                    .addComponent(label_rerata1)
                    .addComponent(label_nim2)
                    .addComponent(label_rerata2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama1)
                    .addComponent(label_grade1)
                    .addComponent(label_nama2)
                    .addComponent(label_grade2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_keterangan1)
                    .addComponent(label_keterangan2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tabelNilaiMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        // TODO add your handling code here
       label_nim2.setText(tabelNilaiMahasiswa.getValueAt(tabelNilaiMahasiswa.getSelectedRow(),0).toString());
       label_nama2.setText(tabelNilaiMahasiswa.getValueAt(tabelNilaiMahasiswa.getSelectedRow(),1).toString());
       label_rerata2.setText(tabelNilaiMahasiswa.getValueAt(tabelNilaiMahasiswa.getSelectedRow(),2).toString());
       label_grade2.setText(tabelNilaiMahasiswa.getValueAt(tabelNilaiMahasiswa.getSelectedRow(),3).toString());
       label_keterangan2.setText(tabelNilaiMahasiswa.getValueAt(tabelNilaiMahasiswa.getSelectedRow(),4).toString());
    }                                                

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        formUtama menu = new formUtama();
        menu.setVisible(true);
        this.getDesktopPane().add(menu);
        this.dispose();
    }                                          

    private void cb_statsActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (cb_stats.getSelectedItem() == "Nilai Rerata") {
          avgTable();
        } else if (cb_stats.getSelectedItem() == "Jumlah Mahasiswa yang Lulus") {
            countTableByMahasiswaLulus();
        } else if (cb_stats.getSelectedItem() == "Jumlah Mahasiswa yang Tidak Lulus") {
            countTableByMahasiswaTidakLulus();
        }
    }                                        

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        data.nim = label_nim2.getText();
        data.nama = label_nama2.getText();
        data.rerata = Integer.parseInt(label_rerata2.getText());
        data.grade = label_grade2.getText();
        data.keterangan = label_keterangan2.getText();
         try {
             data.hapusData();
             JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
             refreshTable();
             refreshData();
             }catch (SQLException ex){
        }  
    }                                         
    
    public void showTable() {
        try {
             st = (Statement) conn.createStatement();
             sql = "SELECT nim, nama, rerata, grade, keterangan FROM nilai_mahasiswa";
             rs = st.executeQuery(sql); 
             tableModel = (DefaultTableModel)tabelNilaiMahasiswa.getModel(); 
             while(rs.next()) {
                 tableModel.addRow(new Object[] {
                 rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
             } );
             }
        } catch (SQLException ex){
        }
    }
    
    public void avgTable() {
        try {
             st = (Statement) conn.createStatement();
             sql = "SELECT AVG(rerata) FROM nilai_mahasiswa";
             rs = st.executeQuery(sql); 
             if(rs.next()) {
                 tfNilaiRerata2.setText(Integer.toString(rs.getInt(1)));
             }
        } catch (SQLException e){
        }
    } 
    
    public void countTableByMahasiswaLulus() {
        try {
             st = (Statement) conn.createStatement();
             sql = "SELECT COUNT(*) FROM nilai_mahasiswa WHERE keterangan = 'Dinyatakan Lulus'";
             rs = st.executeQuery(sql); 
             if(rs.next()) {
                tfNilaiRerata2.setText(Integer.toString(rs.getInt(1)));
             }
        } catch (SQLException e){
        }
    }
    
    public void countTableByMahasiswaTidakLulus() {
        try {
             st = (Statement) conn.createStatement();
             sql = "SELECT COUNT(*) FROM nilai_mahasiswa WHERE keterangan = 'Dinyatakan Tidak Lulus'";
             rs = st.executeQuery(sql); 
             if(rs.next()) {
                tfNilaiRerata2.setText(Integer.toString(rs.getInt(1)));
             }
        } catch (SQLException e){
        }
    }
    
    public void refreshTable() {
        try {
             Statement st = (Statement) conn.createStatement();
             String sql = "SELECT * FROM nilai_mahasiswa";
             ResultSet rs = st.executeQuery(sql); 
             DefaultTableModel tableModel;
             tableModel = (DefaultTableModel)tabelNilaiMahasiswa.getModel(); 
             tableModel.getDataVector().removeAllElements();
             tableModel.fireTableDataChanged();
             tableModel.setRowCount(0);
             while(rs.next()) {
                 tableModel.addRow(new Object[] {
                 rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)
             } );
             }
        } catch (SQLException ex){

        }
    }
      
    public void refreshData() {
       label_nim2.setText("-");
       label_nama2.setText("-");
       label_rerata2.setText("-");
       label_grade2.setText("-");
       label_keterangan2.setText("-");
    }
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTabelNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTabelNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTabelNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTabelNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTabelNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JComboBox<String> cb_stats;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label_detail;
    private javax.swing.JLabel label_grade1;
    private javax.swing.JLabel label_grade2;
    private javax.swing.JLabel label_keterangan1;
    private javax.swing.JLabel label_keterangan2;
    private javax.swing.JLabel label_nama1;
    private javax.swing.JLabel label_nama2;
    private javax.swing.JLabel label_nim1;
    private javax.swing.JLabel label_nim2;
    private javax.swing.JLabel label_rerata1;
    private javax.swing.JLabel label_rerata2;
    private javax.swing.JTable tabelNilaiMahasiswa;
    private javax.swing.JTextField tfNilaiRerata2;
    // End of variables declaration                   
}
