package mahasiswa;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author dwicd
 */
public class formInputNilai extends javax.swing.JInternalFrame {

    int nilaiRerata;
    String grade;
    String keterangan;
    
    /**
     * Creates new form formInputNilai
     */
    public formInputNilai() {
        initComponents();
        this.setTitle("Form Input Nilai Mahasiswa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        label_nama1 = new javax.swing.JLabel();
        label_nim1 = new javax.swing.JLabel();
        label_nilaiTugas = new javax.swing.JLabel();
        label_nilaiKuis = new javax.swing.JLabel();
        label_nilaiMidTerm = new javax.swing.JLabel();
        label_nilaiFinalTerm = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNim = new javax.swing.JTextField();
        tfNilaiTugas = new javax.swing.JTextField();
        tfNilaiKuis = new javax.swing.JTextField();
        tfNilaiMidTerm = new javax.swing.JTextField();
        tfNilaiFinalTerm = new javax.swing.JTextField();
        label_nama2 = new javax.swing.JLabel();
        label_nama3 = new javax.swing.JLabel();
        label_nim2 = new javax.swing.JLabel();
        label_nim3 = new javax.swing.JLabel();
        label_rerata1 = new javax.swing.JLabel();
        label_rerata2 = new javax.swing.JLabel();
        label_grade1 = new javax.swing.JLabel();
        label_grade2 = new javax.swing.JLabel();
        label_ktr1 = new javax.swing.JLabel();
        label_ktr2 = new javax.swing.JLabel();
        btn_hitung = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_nama1.setText("Nama");

        label_nim1.setText("NIM");

        label_nilaiTugas.setText("Nilai Tugas");

        label_nilaiKuis.setText("Nilai Kuis");

        label_nilaiMidTerm.setText("Nilai UTS");

        label_nilaiFinalTerm.setText("Nilai UAS");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        tfNilaiTugas.setText("0");

        tfNilaiKuis.setText("0");

        tfNilaiMidTerm.setText("0");

        tfNilaiFinalTerm.setText("0");

        label_nama2.setText("Nama :");

        label_nama3.setText("N/A");

        label_nim2.setText("NIM :");

        label_nim3.setText("N/A");

        label_rerata1.setText("Rerata :");

        label_rerata2.setText("-");

        label_grade1.setText("Grade :");

        label_grade2.setText("-");

        label_ktr1.setText("Keterangan :");

        label_ktr2.setText("N/A");

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama1)
                            .addComponent(label_nim1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNama)
                            .addComponent(tfNim, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nilaiKuis)
                                    .addComponent(label_nilaiMidTerm)
                                    .addComponent(label_nilaiFinalTerm))
                                .addGap(21, 21, 21))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_nilaiTugas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNilaiFinalTerm)
                            .addComponent(tfNilaiKuis)
                            .addComponent(tfNilaiTugas)
                            .addComponent(tfNilaiMidTerm))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_nama2)
                            .addComponent(label_nim2)
                            .addComponent(label_grade1))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_grade2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label_nama3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_nim3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_rerata1)
                        .addGap(45, 45, 45)
                        .addComponent(label_rerata2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_ktr1)
                        .addGap(18, 18, 18)
                        .addComponent(label_ktr2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_hitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_keluar)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nama1)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nama2)
                    .addComponent(label_nama3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nim1)
                    .addComponent(tfNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_nim2)
                    .addComponent(label_nim3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_rerata2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label_rerata1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_nilaiTugas)
                        .addComponent(tfNilaiTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_grade1)
                        .addComponent(label_grade2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_nilaiKuis)
                        .addComponent(tfNilaiKuis, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_ktr2)
                        .addComponent(label_ktr1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_nilaiMidTerm)
                        .addComponent(tfNilaiMidTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nilaiFinalTerm)
                    .addComponent(tfNilaiFinalTerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hitung)
                    .addComponent(btn_reset)
                    .addComponent(btn_simpan)
                    .addComponent(btn_keluar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        hitung(0, 0, 0, 0);
        label_nama3.setText(tfNama.getText());
        label_nim3.setText(tfNim.getText());
        label_rerata2.setText(Integer.toString(nilaiRerata));
        decisionMaker();
        label_grade2.setText(grade);
        label_ktr2.setText(keterangan);
    }                                          

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        cleanTextField();
    }                                         

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        mahasiswa_model data = new mahasiswa_model();
        data.nim = label_nim3.getText();
        data.nama = label_nama3.getText();
        data.rerata = Integer.parseInt(label_rerata2.getText());
        data.grade = label_grade2.getText();
        data.keterangan = label_ktr2.getText();
        if (label_rerata2.getText() == "-" || label_grade2.getText() == "-" || label_ktr2.getText() == "-") {
        JOptionPane.showMessageDialog(null, "Silakan masukkan data secara lengkap!", "Verification Error!", JOptionPane.ERROR_MESSAGE); 
        } else {
        try {
        data.simpanNilai();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        cleanTextField();
        } catch (SQLException e) {
          JOptionPane.showMessageDialog(null, e);
        }
      }
    }                                          

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        formUtama menu = new formUtama();
        menu.setVisible(true);
        this.getDesktopPane().add(menu);
        this.dispose();
    }                                          
    
    private int hitung(int nilaiTugas, int nilaiKuis, int nilaiMidTerm, int nilaiFinalTerm) {
        nilaiTugas = Integer.parseInt(tfNilaiTugas.getText());
        nilaiKuis = Integer.parseInt(tfNilaiKuis.getText());
        nilaiMidTerm = Integer.parseInt(tfNilaiMidTerm.getText());
        nilaiFinalTerm = Integer.parseInt(tfNilaiFinalTerm.getText());
        nilaiRerata = ((nilaiTugas + nilaiKuis + nilaiMidTerm + nilaiFinalTerm)/4);
        return nilaiRerata;
    }
    
    private void decisionMaker() {
        if (nilaiRerata >= 90) {
            grade = "A";
        } else if (nilaiRerata >= 85) {
            grade = "A-"; 
        } else if (nilaiRerata >= 80) {
            grade = "B+";
        } else if (nilaiRerata >= 75) {
            grade = "B";
        } else if (nilaiRerata >= 67) {
            grade = "B-";
        } else if (nilaiRerata >= 60) {
            grade = "C";
        } else if (nilaiRerata >= 50) {
            grade = "D";
        } else if (nilaiRerata > 0) {
            grade = "E";
        } else {
            grade = "F";
        }
        
        if (nilaiRerata >= 50) {
            keterangan = "Dinyatakan Lulus";
        } else {
            keterangan = "Dinyatakan Tidak Lulus";
        }
    }
    
    private void cleanTextField() {
        tfNama.setText("");
        tfNim.setText("");
        tfNilaiKuis.setText("0");
        tfNilaiTugas.setText("0");
        tfNilaiMidTerm.setText("0");
        tfNilaiFinalTerm.setText("0");
        label_nama3.setText("N/A");
        label_nim3.setText("N/A");
        label_rerata2.setText("0");
        label_ktr2.setText("N/A");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formInputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formInputNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel label_grade1;
    private javax.swing.JLabel label_grade2;
    private javax.swing.JLabel label_ktr1;
    private javax.swing.JLabel label_ktr2;
    private javax.swing.JLabel label_nama1;
    private javax.swing.JLabel label_nama2;
    private javax.swing.JLabel label_nama3;
    private javax.swing.JLabel label_nilaiFinalTerm;
    private javax.swing.JLabel label_nilaiKuis;
    private javax.swing.JLabel label_nilaiMidTerm;
    private javax.swing.JLabel label_nilaiTugas;
    private javax.swing.JLabel label_nim1;
    private javax.swing.JLabel label_nim2;
    private javax.swing.JLabel label_nim3;
    private javax.swing.JLabel label_rerata1;
    private javax.swing.JLabel label_rerata2;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNilaiFinalTerm;
    private javax.swing.JTextField tfNilaiKuis;
    private javax.swing.JTextField tfNilaiMidTerm;
    private javax.swing.JTextField tfNilaiTugas;
    private javax.swing.JTextField tfNim;
    // End of variables declaration                   
}
